SET CONSTRAINTS FOR payment DISABLED;
SET TRIGGERS FOR payment DISABLED;

SET CONSTRAINTS FOR rental DISABLED;
SET TRIGGERS FOR rental DISABLED;

SET INDEXES FOR customer DISABLED;
SET CONSTRAINTS FOR customer DISABLED;
SET TRIGGERS FOR customer DISABLED;

SET CONSTRAINTS FOR film_category DISABLED;
SET TRIGGERS FOR film_category DISABLED;

SET CONSTRAINTS FOR film_text DISABLED;
SET TRIGGERS FOR film_text DISABLED;

SET CONSTRAINTS FOR film_actor DISABLED;
SET TRIGGERS FOR film_actor DISABLED;

SET CONSTRAINTS FOR inventory DISABLED;
SET TRIGGERS FOR inventory DISABLED;

SET CONSTRAINTS FOR film DISABLED;
SET TRIGGERS FOR film DISABLED;

SET CONSTRAINTS FOR category DISABLED;
SET TRIGGERS FOR category DISABLED;

SET CONSTRAINTS fk_staff_store DISABLED;
SET TRIGGERS FOR staff DISABLED;

SET CONSTRAINTS FOR store DISABLED;
SET TRIGGERS FOR store DISABLED;

-- Circular referential dependency forces this
SET CONSTRAINTS fk_staff_address DISABLED;

SET INDEXES FOR actor DISABLED;
SET CONSTRAINTS FOR actor DISABLED;
SET TRIGGERS FOR actor DISABLED;

SET CONSTRAINTS FOR address DISABLED;
SET TRIGGERS FOR address DISABLED;

SET CONSTRAINTS FOR city DISABLED;
SET TRIGGERS FOR city DISABLED;

SET CONSTRAINTS FOR country DISABLED;
SET TRIGGERS FOR country DISABLED;

SET CONSTRAINTS FOR language DISABLED;
SET TRIGGERS FOR language DISABLED;

DELETE FROM payment
;
DELETE FROM rental
;
DELETE FROM customer
;
DELETE FROM film_category
;
DELETE FROM film_text
;
DELETE FROM film_actor
;
DELETE FROM inventory
;
DELETE FROM film
;
DELETE FROM category
;
DELETE FROM staff
;
DELETE FROM store
;
DELETE FROM actor
;
DELETE FROM address
;
DELETE FROM city
;
DELETE FROM country
;
DELETE FROM language
;

INSERT INTO payment SELECT * FROM e_payment;
INSERT INTO rental SELECT * FROM e_rental;
INSERT INTO customer SELECT * FROM e_customer;
INSERT INTO film_category SELECT * FROM e_film_category;
INSERT INTO film_text SELECT * FROM e_film_text;
INSERT INTO film_actor SELECT * FROM e_film_actor;
INSERT INTO inventory SELECT * FROM e_inventory;
INSERT INTO film SELECT * FROM e_film;
INSERT INTO category SELECT * FROM e_category;
INSERT INTO staff SELECT * FROM e_staff;
INSERT INTO store SELECT * FROM e_store;
INSERT INTO actor SELECT * FROM e_actor;
INSERT INTO address SELECT * FROM e_address;
INSERT INTO city SELECT * FROM e_city;
INSERT INTO country SELECT * FROM e_country;
INSERT INTO language SELECT * FROM e_language;

SET CONSTRAINTS FOR language ENABLED;
SET TRIGGERS FOR language ENABLED;

SET CONSTRAINTS FOR country ENABLED;
SET TRIGGERS FOR country ENABLED;

SET CONSTRAINTS FOR city ENABLED;
SET TRIGGERS FOR city ENABLED;

SET CONSTRAINTS FOR address ENABLED;
SET TRIGGERS FOR address ENABLED;

SET INDEXES FOR actor ENABLED;
SET CONSTRAINTS FOR actor ENABLED;
SET TRIGGERS FOR actor ENABLED;

SET CONSTRAINTS FOR store ENABLED;
SET TRIGGERS FOR store ENABLED;

SET CONSTRAINTS FOR staff ENABLED;
SET TRIGGERS FOR staff ENABLED;

SET CONSTRAINTS FOR category ENABLED;
SET TRIGGERS FOR category ENABLED;

SET CONSTRAINTS FOR film ENABLED;
SET TRIGGERS FOR film ENABLED;

SET CONSTRAINTS FOR inventory ENABLED;
SET TRIGGERS FOR inventory ENABLED;

SET CONSTRAINTS FOR film_actor ENABLED;
SET TRIGGERS FOR film_actor ENABLED;

SET CONSTRAINTS FOR film_text ENABLED;
SET TRIGGERS FOR film_text ENABLED;

SET CONSTRAINTS FOR film_category ENABLED;
SET TRIGGERS FOR film_category ENABLED;

SET INDEXES FOR customer ENABLED;
SET CONSTRAINTS FOR customer ENABLED;
SET TRIGGERS FOR customer ENABLED;

SET CONSTRAINTS FOR rental ENABLED;
SET TRIGGERS FOR rental ENABLED;

SET CONSTRAINTS FOR payment ENABLED;
SET TRIGGERS FOR payment ENABLED;

