CREATE EXTERNAL TABLE e_payment SAMEAS payment USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_payment.unl"));
CREATE EXTERNAL TABLE e_rental SAMEAS rental USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_rental.unl"));
CREATE EXTERNAL TABLE e_customer SAMEAS customer USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_customer.unl"));
CREATE EXTERNAL TABLE e_film_category SAMEAS film_category USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_film_category.unl"));
CREATE EXTERNAL TABLE e_film_text SAMEAS film_text USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_film_text.unl"));
CREATE EXTERNAL TABLE e_film_actor SAMEAS film_actor USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_film_actor.unl"));
CREATE EXTERNAL TABLE e_inventory SAMEAS inventory USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_inventory.unl"));
CREATE EXTERNAL TABLE e_film SAMEAS film USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_film.unl"));
CREATE EXTERNAL TABLE e_category SAMEAS category USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_category.unl"));
CREATE EXTERNAL TABLE e_staff SAMEAS staff USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_staff.unl"));
CREATE EXTERNAL TABLE e_store SAMEAS store USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_store.unl"));
CREATE EXTERNAL TABLE e_actor SAMEAS actor USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_actor.unl"));
CREATE EXTERNAL TABLE e_address SAMEAS address USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_address.unl"));
CREATE EXTERNAL TABLE e_city SAMEAS city USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_city.unl"));
CREATE EXTERNAL TABLE e_country SAMEAS country USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_country.unl"));
CREATE EXTERNAL TABLE e_language SAMEAS language USING (DATAFILES ("DISK:/home/informix/sakila/informix-sakila-db/data/e_language.unl"));

INSERT INTO e_payment SELECT * FROM payment;
INSERT INTO e_rental SELECT * FROM rental;
INSERT INTO e_customer SELECT * FROM customer;
INSERT INTO e_film_category SELECT * FROM film_category;
INSERT INTO e_film_text SELECT * FROM film_text;
INSERT INTO e_film_actor SELECT * FROM film_actor;
INSERT INTO e_inventory SELECT * FROM inventory;
INSERT INTO e_film SELECT * FROM film;
INSERT INTO e_category SELECT * FROM category;
INSERT INTO e_staff SELECT * FROM staff;
INSERT INTO e_store SELECT * FROM store;
INSERT INTO e_actor SELECT * FROM actor;
INSERT INTO e_address SELECT * FROM address;
INSERT INTO e_city SELECT * FROM city;
INSERT INTO e_country SELECT * FROM country;
INSERT INTO e_language SELECT * FROM language;
